PrecisoPRO/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;
using PrecisoPRO.Interfaces;
using PrecisoPRO.Models;
using PrecisoPRO.Models.ViewModels;
using PrecisoPRO.Services;
using System.Data;
using System.Drawing;
using X.PagedList;

namespace PrecisoPRO.Controllers
{
    public class EmpresaController : Controller
    {
       
        //contexto do banco de dados
        private readonly IEmpresaRepository _empresaRepository;
        private readonly IEstadoRepository _estadoRepository;
        private readonly IAssociarEmpUf _associarEmpUf;
        private readonly INatJuridica _natJuridica;
        private readonly IRegimeJuridico _regimeJuridico;


        IEnumerable<Empresa>? listaEmpresas; //Lista enumerada
        IEnumerable<Estado>? listaEstados; //lista de estados
        IEnumerable<NaturezaJuridica>? listaNatJuridica; //lista as naturezas juridicas
        IEnumerable<AssociarEmpUf>? listaAssociarEmpUF;
        IEnumerable<RegimeJuridico>? listaRegimeJuridicos;
        int contSalvos = 0;
        public EmpresaController(IEmpresaRepository empresaRepository, IEstadoRepository estadoRepository, IAssociarEmpUf associarEmpUf, INatJuridica natJuridica, IRegimeJuridico regJuridico)
        {
            _empresaRepository = empresaRepository;
            _estadoRepository = estadoRepository;
            _associarEmpUf = associarEmpUf;
            _natJuridica = natJuridica;
            _regimeJuridico = regJuridico;


        }   
        public async Task<IActionResult> Index(string cnpj, string razao, string cidade, string fantasia, string estado, int numPagina = 1) 
        {
            this.listaEmpresas = await _empresaRepository.GetAllAsyncNoTracking();
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();
            this.listaRegimeJuridicos = await _regimeJuridico.GetAllAsyncNoTracking();
            if (cnpj != null)
            {
                this.listaEmpresas = this.listaEmpresas.Where(x => x.Cnpj.Contains(cnpj)).ToList();
                ViewBag.Cnpj = cnpj;
            }

            if (razao != null)
            {
                this.listaEmpresas = this.listaEmpresas.Where(x=>x.Razao.Contains(razao)).ToList();
                ViewBag.Razao = razao;
            }
            if(cidade != null)
            {
                this.listaEmpresas = this.listaEmpresas.Where(x => x.Cidade.Contains(cidade)).ToList();
                ViewBag.Cidade = cidade;
            }
            if (fantasia != null)
            {
                this.listaEmpresas = this.listaEmpresas.Where(x => x.Fantasia.Contains(fantasia)).ToList();
                ViewBag.Fantasia = fantasia;
            }
           
           
            if(estado !=null && estado != "")
            {
                this.listaEmpresas = this.listaEmpresas.Where(x => x.UF.Contains(estado)).ToList();
                ViewBag.Estado = estado;
            }
           
           
            //Busca os Estados
            ViewBag.Estados = this.listaEstados.ToList();
            ViewBag.RegimesJuridicos = this.listaRegimeJuridicos.ToList();
            //passa inicialmente dois parametros, o numero da pagina e o tamanho da página
            return View(this.listaEmpresas.ToPagedList(numPagina, 8));
        }

        //create
        public async Task<IActionResult> Incluir()
        {
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();
            this.listaNatJuridica = await _natJuridica.GetAllAsyncNoTracking();
            this.listaRegimeJuridicos = await _regimeJuridico.GetAllAsyncNoTracking();
            //Busca os Estados
            ViewBag.Estados = this.listaEstados.ToList();
            ViewBag.NatJuridica = this.listaNatJuridica.ToList();
            ViewBag.RegimeJuridico = this.listaRegimeJuridicos.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Incluir(EmpresaViewModel? empresaVM)
        {

            if (ModelState.IsValid)
            {
               
                var empresa = new Empresa
                {
                    Ie = empresaVM.Ie,
                    Im = empresaVM.Im,
                    Cnpj = empresaVM.Cnpj,
                    Razao = empresaVM.Razao,
                    NMei = empresaVM.NMei,
                    Fantasia = empresaVM.Fantasia,
                    NatJuridica = empresaVM.NatJuridica,
                    RegJuridico = empresaVM.RegJuridico,
                    AtvPrincipal = empresaVM.AtvPrincipal,
                    Cep = empresaVM.Cep,
                    Endereco = empresaVM.Endereco,
                    Numero = empresaVM.Numero,
                    Complemento = empresaVM.Complemento,
                    Bairro = empresaVM.Bairro,
                    Cidade = empresaVM.Cidade,
                    UF = empresaVM.UF,
                    Referencia = empresaVM.Referencia,
                    Principal = empresaVM.Principal,
                    Telefone = empresaVM.Telefone,
                    Celular = empresaVM.Celular,
                    Email = empresaVM.Email,
                    SitCadastral = empresaVM.SitCadastral,
                    MotDescCred = empresaVM.MotDescCred,
                    Nire = empresaVM.Nire,
                    NomeContador = empresaVM.NomeContador,
                    CrcContador = empresaVM.CrcContador,
                    NomeResponsavel = empresaVM.NomeResponsavel,
                    CrcResponsavel = empresaVM.CrcResponsavel,
                    TelAlternativo = empresaVM.TelAlternativo,
                    CelAlternativo = empresaVM.CelAlternativo,
                    EmailAlternativo = empresaVM.EmailAlternativo,
                    LoginDteSefaz = empresaVM.LoginDteSefaz,
                    SenhaDteSefaz = empresaVM.SenhaDteSefaz,
                    CpfRepresentante = empresaVM.CpfRepresentante,
                    Anotacoes = empresaVM.Anotacoes,
                    Data_Cad = DateTime.Now,
                    Data_Alt = DateTime.Now


                };
                try
                {
                    _empresaRepository.Adicionar(empresa);
                    TempData["Success"] = "Registro SALVO com sucesso";
                    return RedirectToAction("Index");
                }
                catch(Exception e)
                {
                    TempData["Error"] = "Probelmas ao salvar o registro, tente novamente";
                    return RedirectToAction("Index");
                }
               
                
            }
            else
            {
                ModelState.AddModelError("", "ERRO");
            }
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();
            this.listaNatJuridica = await _natJuridica.GetAllAsyncNoTracking();
            this.listaRegimeJuridicos = await _regimeJuridico.GetAllAsyncNoTracking();
            //Busca os Estados
            ViewBag.Estados = this.listaEstados.ToList();
            ViewBag.NatJuridica = this.listaNatJuridica.ToList();
            ViewBag.RegimeJuridico = this.listaRegimeJuridicos.ToList();
            return View(empresaVM);
        }

        public async Task<IActionResult>AlterarRegime(int id, string regimeNome)
        {
            //Seleciona a Empresa pelo ID e cria um objeto dela
            Empresa empresa = await _empresaRepository.GetByIdAsync(id);

            //Carrega a lista de Regimejuridico
            this.listaRegimeJuridicos = await _regimeJuridico.GetAllAsyncNoTracking();

            //Asssocia o valor do parametro a uma variavel
            string regime = regimeNome;

            //Busca o objeto em forma de var do regime juridico
            var regimeJuridico = this.listaRegimeJuridicos.FirstOrDefault(r => r.Nome == regimeNome);

            //verifica o retorno e associa a variavel idregime
            if(regimeJuridico != null)
            {
                int regimeId = regimeJuridico.Id;
                empresa.RegJuridico = regimeId;
            }

            try
            {
                _empresaRepository.Update(empresa);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["Error"] = "Probelmas ao salvar o registro, tente novamente";
                return RedirectToAction("Index");
            }


            ViewBag.RegimesJuridicos = this.listaRegimeJuridicos.ToList();

            return View(empresa);
        }
        public async Task<IActionResult> AssociarIndividual(int id)
        {
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();
            Empresa empresa = await _empresaRepository.GetByIdAsync(id);

            //Busca os Estados
            ViewBag.Estados = this.listaEstados.ToList();
         
            return View(empresa);
        }

        [HttpPost]
        public async Task<IActionResult> AssociarIndividual(string? empresa, List<string> checkUf)
        {
            this.listaAssociarEmpUF = await _associarEmpUf.GetAllAsyncNoTracking();
            int id = int.Parse(empresa);



            if (ModelState.IsValid)
            {
                //agora percorrer o array e associar a empresa que veio no parametro a cada estado que foi selecionado
                foreach (var valorCheckbox in checkUf)
                {
                    //buscar peplo id da empresa
                    var jaExisteUf = this.listaAssociarEmpUF.Where(x => x.IdEstado.Equals(int.Parse(valorCheckbox)) && x.IdEmpresa.Equals(id)).ToList();


                    if (jaExisteUf.Count == 0)
                    {
                        var associar = new AssociarEmpUf
                        {
                            IdEmpresa = id,
                            IdEstado = int.Parse(valorCheckbox),
                            Data_Cad = DateTime.Now
                        };
                        try
                        {

PrecisoPRO/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using PrecisoPRO.Filters;
using PrecisoPRO.Interfaces;
using PrecisoPRO.Models;
using PrecisoPRO.Models.ViewModels;
using X.PagedList;

namespace PrecisoPRO.Controllers
{
    [PaginaParaUsuarioLogado]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly IEmpresaRepository _empresaRepository;
        IEnumerable<Usuario>? listaUsuario;
        IEnumerable<Empresa>? listaEmpresas;
        public UsuarioController(IUsuarioRepository usuarioRepository, IEmpresaRepository empresaRepository)
        {
            _usuarioRepository = usuarioRepository;
            _empresaRepository = empresaRepository;
        }

        // GET: Usuario
        public async Task<IActionResult> Index(string nome, string login, int numPagina = 1)
        {
            this.listaUsuario = await _usuarioRepository.GetAll();

            if (nome != null)
            {
                this.listaUsuario = this.listaUsuario.Where(x => x.Nome.Contains(nome)).ToList();
                ViewBag.Nome = nome;
            }
            if (login != null)
            {
                this.listaUsuario = this.listaUsuario.Where(x => x.Login.Contains(login)).ToList();
                ViewBag.Login = login;
            }
            return View(this.listaUsuario.ToPagedList(numPagina, 8));

        }
        public async Task<IActionResult> Incluir()
        {
            this.listaEmpresas = await _empresaRepository.GetAll();
            ViewBag.Empresas = this.listaEmpresas.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Incluir(UsuarioViewModel? usuarioVM)
        {
            if (ModelState.IsValid)
            {

                var usuario = new Usuario
                {
                    Nome = usuarioVM.Nome,
                    Login = usuarioVM.Login.ToLower(),
                    Celular = usuarioVM.Celular,
                    Senha = usuarioVM.Senha,
                    Email = usuarioVM.Email,
                    EmpresaId = usuarioVM.EmpresaId,
                    Status = 1,
                    Data_Cad = DateTime.Now,
                    Data_Alt = DateTime.Now

                };
                try
                {
                    _usuarioRepository.Adicionar(usuario);
                    TempData["Success"] = "usuario adicionado com sucesso";
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["Error"] = "Houve um erro ao adicionar o usuario, tente novamente";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                ModelState.AddModelError("", "ERRO");
            }
            this.listaEmpresas = await _empresaRepository.GetAll();
            ViewBag.Empresas = this.listaEmpresas.ToList();
            return View(usuarioVM);
        }
        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
            try
            {
                if (ModelState.IsValid)
                {

                }
                return View("Index");

            }
            catch (Exception)
            {
                TempData["MessageErro"] = "Houve um erro";
                return RedirectToAction("Index");
            }
        }
    }
}

PrecisoPRO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*  <title id="titulo" class="pro-titulo">@ViewData["Title"] - PrecisoPRO</title> *@
    <title id="titulo" class="pro-titulo">@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">
    <!----======== CSS - PAULO ======== -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dev_paulo.css" asp-append-version="true" />

    <!----======== CSS - MATHEUS ======== -->
    <link href="~/css/css-layout.css" rel="stylesheet" />
    <!----===== Boxicons CSS - MATHEUS ===== -->
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>

    <style>
        ul li.nav-item {
            transition: .90s !important;
        }
    </style>

</head>
<body>

    <section class="fixed-top bg-white py-1 " id="Navbartop">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 dropdown-center">
                    <ul class="nav">
                        <li class="nav-item px-2">
                            <img src="~/lib/IMG/PRECISO LUPA.png" class="img-fluid" width="40" />
                        </li>

                        <!----===== DROPDOWN INÍCIO ===== -->
                        <li class="nav-item">
                            <a class="nav-link text-black dropdown-toggle borderbutton" type="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">
                                <img src="~/lib/IMG/iníciocinza.png" class="img-fluid py-2" width="30" />
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Início</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <!----===== DROPDOWN FIM ===== -->
                        <!----===== DROPDOWN INÍCIO ===== -->
                        <li class="nav-item">
                            <a class="nav-link text-white dropdown-toggle borderbutton" type="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">

                                <img src="~/lib/IMG/tabelascinza.png" class="img-fluid py-2" width="30" />

                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/Empresa">Empresa</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <!----===== DROPDOWN FIM ===== -->
                        <!----===== DROPDOWN INÍCIO ===== -->
                        <li class="nav-item">
                            <a class="nav-link text-black dropdown-toggle borderbutton" type="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">
                                <img src="~/lib/IMG/cadastrar.png" class="img-fluid py-2" width="33" />
                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Início</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <!----===== DROPDOWN FIM ===== -->

                        <!----===== DROPDOWN INÍCIO ===== -->
                        <li class="nav-item">
                            <a class="nav-link text-white dropdown-toggle borderbutton" type="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">
                                <img src="~/lib/IMG/notificacoescinza.png" class="img-fluid py-2" width="30" />
                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/Empresa">Empresa</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <!----===== DROPDOWN FIM ===== -->

                        <!----===== IMAGEM PERFIL ===== -->
                        <li class="nav-item ms-auto">
                            <img src="~/lib/IMG/usermobile.png" class="img-fluid" width="40" />
                        </li>
                        <!----===== FIM IMAGEM PERFIL ===== -->

                      

                    </ul>


                </div>
            </div>
        </div>
    </section>
    <!----===== INÍCIO SIDEBAR ===== -->
    <section>
        <nav class="sidebar close" id="sideclose">
            <!----===== DEFAULT  ===== -->
            @await Component.InvokeAsync("Menu")
            <!----===== DEFAULT ===== -->
            <!----===== INÍCIO MENU SIDEBAR ===== -->
            <!----===== INÍCIO MENU SIDEBAR ===== -->
            <div class="menu-bar">
                <div class="menu border-top">
                    <ul>
                        <li class="search-box ">
                            <i data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Buscar" class='bx bx-search icon'></i>
                            <input  type="text" class=" fs-6_5" placeholder="Buscar">
                        </li>
                    </ul>
                    <!----===== INÍCIO TESTE DROPDOWN ===== -->
                    <!----===== FIM TESTE DROPDOWN ===== -->
                    <ul class="menu-links">
                        <li class="nav-link">


                            <a href="/home" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Início">

                                <i class='bx bx-home-alt icon fs-4'></i>
                              
                                <span class="text nav-text fs-6_5">Início</span>
                            </a>
                        </li>

                        <li class="nav-link">
                                                     
                             <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Cadastrar Empresa" asp-controller="Empresa" asp-action="Index">
                                <i class="fa-regular fa-building  icon"></i>
                                <span class="text nav-text fs-6_5">Cadastrar Empresas</span>
                            </a>
                        </li>


                        <li class="nav-link">
                            <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Cadastrar Usuário" asp-controller="Usuario" asp-action="Index">
                                <i class="fa-regular fa-user icon"></i>
                                <span class="text nav-text fs-6_5">Cadastrar Usuários</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Configurar CND's" asp-controller="Buscarcnds" asp-action="Index">
                                <i class="fa-solid fa-laptop-file icon"></i>
                                <span class="text nav-text fs-6_5">Configurar CNDs</span>
                            </a>
                        </li>


                        <li class="nav-link">
                            <a href="#" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Notificações">
                                <i class='bx bx-bell icon'></i>
                                <span class="text pe-2 nav-text">Notificações</span>
                                <span class="badge px-2 text-white  badge-pill badge-warning">3</span>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="bottom-content">
                    <ul>
                        <li class="">


                            <a href="/login" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Sair">

                                <i class='bx bx-log-out icon'></i>
                                <span class="text nav-text">Sair</span>
                            </a>
                        </li>
                    </ul>
                    <ul>
                        <li class="mode py-2">
                            <div class="sun-moon">
                                <i class='bx bx-moon icon moon'></i>
                                <i class='bx bx-sun icon sun'></i>
                            </div>
                            <span class="mode-text text">Dark mode</span>


                            <div class="toggle-switch">
                                <span class="switch"></span>
                            </div>
                        </li>
                    </ul>
                    <div class="mode-img pt-2 border-top">
                        <img src="lib/IMG/logobottom.png" width="190" />
                    </div>
                </div>
            </div>

        </nav>
        <section class="home" id="renderbody">
            <div class="container-fluid">
                @* <button class="btn btn-danger" id="esconderMenu" onclick="esconderMenu()">FECHAR</button> *@
                <div class="text">@RenderBody()</div>
            </div>
        </section>
    </section>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/lib/jquery/jquery.mask.min.js"></script>
    <script src="~/lib/jquery/jquery.maskedinput.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/sidebar.js"></script>
    <!----===== ATIVAR DICAS ===== -->
    <script>
        $(function () {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
            // $('[data-toggle="tooltip"]').tooltip()
        })
    </script>



    <!----===== FIM ATIVAR DICAS ===== -->

    <!----===== TESTE ===== -->
    <script>
        $(function () {
            // Função para verificar se a barra lateral está fechada
            function isSidebarClosed() {
                return $('.sidebar').hasClass('close');
            }

            // Adiciona um ouvinte de eventos aos elementos com atributo 'data-bs-toggle="tooltip"'
            $('[data-bs-toggle="tooltip"]').tooltip({
                // Exibe ou oculta o tooltip com base na condição
                enabled: isSidebarClosed(),
            });

            // Adiciona um ouvinte de eventos para ajustar a visibilidade do tooltip ao abrir/fechar a barra lateral
            $('.toggle').click(function () {
                const tooltips = $('[data-bs-toggle="tooltip"]').data('bs.tooltip');
                tooltips.forEach(tooltip => {
                    tooltip.config.enabled = isSidebarClosed();
                });
            });
        });
    </script>


    <!----===== FIM ATIVAR DICAS ===== -->
    <!----===== SCRIPT PARA RESPONSIVIDADE ===== -->
    <script>
        // Verificar a largura da tela e modificar a classe do elemento
        function verificarLarguraDaTela() {
            //Pega os elementos que contem a classe prn-resp-td
            var elementosTR = document.querySelectorAll('tr.prn-resp-td');

            //verifica o tamanho da tela
            if (window.innerWidth <= 700) {

                // Loop para aplicar a mudança a cada elemento
                elementosTR.forEach(function (elemento) {
                    // Faça as alterações necessárias em cada elemento, adicionando fs-6
                    elemento.classList.add('fs-6'); // Adiciona uma nova classe, se necessário

                });


            }
            else {
                // Loop para aplicar a mudança a cada elemento
                elementosTR.forEach(function (elemento) {
                    // Faça as alterações necessárias em cada elemento removendo a classe fs-6

                    elemento.classList.remove('fs-6'); // Adiciona uma nova classe, se necessário
                });
            }

        }

        // Chamar a função quando a página é carregada
        verificarLarguraDaTela();

        // Chamar a função sempre que a largura da tela for alterada
        window.addEventListener('resize', verificarLarguraDaTela);
    </script>
    <!----===== FIM SCRIPT PARA RESPONSIVIDADE ===== -->
   

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrecisoPRO/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrecisoPRO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrecisoPRO.styles.css" asp-append-version="true" />
</head>
<body>
   <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrecisoPRO/Views/Shared/_LayoutModais.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
   

</head>
<body>
   
  

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery/jquery.mask.min.js"></script>
    <script src="~/lib/jquery/jquery.maskedinput.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/sidebar.js"></script>


    <script>
        $(function () {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
            // $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>